/* eslint-disable */
import React from "react";
import { getOverrideProps } from "@aws-amplify/ui-react/internal";
import {
  Divider,
  Flex,
  SelectField,
  Text,
  TextField,
} from "@aws-amplify/ui-react";
import { useStore } from "../store";
import { AppCart } from "./AppCart";
export default function AppFormCheckout(props) {
  const { overrides: overridesProp, ...rest } = props;
  const overrides = { ...overridesProp };
  const cart = useStore((state) => state.cart);
  return (
    <Flex
      gap="24px"
      direction="row"
      width="1160px"
      alignItems="flex-start"
      position="relative"
      padding="0px 0px 0px 0px"
      {...rest}
      {...getOverrideProps(overrides, "Flex")}
    >
      <Flex
        gap="0"
        direction="row"
        width="667px"
        alignItems="flex-start"
        grow="1"
        basis="667px"
        height="1148px"
        position="relative"
        padding="32px 0px 32px 0px"
        backgroundColor="rgba(255,255,255,1)"
        {...getOverrideProps(overrides, "Flex.Flex[0]")}
      >
        <Flex
          gap="32px"
          direction="column"
          width="667px"
          justifyContent="center"
          alignItems="center"
          grow="1"
          basis="667px"
          height="1084px"
          position="relative"
          padding="0px 0px 0px 0px"
          {...getOverrideProps(overrides, "Flex.Flex[0].Flex[0]")}
        >
          <Flex
            gap="24px"
            direction="column"
            shrink="0"
            alignSelf="stretch"
            objectFit="cover"
            position="relative"
            padding="0px 32px 0px 32px"
            {...getOverrideProps(overrides, "Flex.Flex[0].Flex[0].Flex[0]")}
          >
            <Text
              fontFamily="Inter"
              fontSize="16px"
              fontWeight="700"
              color="rgba(13,26,38,1)"
              lineHeight="24px"
              textAlign="left"
              display="flex"
              direction="column"
              justifyContent="flex-start"
              shrink="0"
              position="relative"
              padding="0px 0px 0px 0px"
              whiteSpace="pre-wrap"
              children="Info"
              {...getOverrideProps(
                overrides,
                "Flex.Flex[0].Flex[0].Flex[0].Text[0]"
              )}
            ></Text>
            <TextField
              display="flex"
              shrink="0"
              alignSelf="stretch"
              objectFit="cover"
              size="large"
              variation="default"
              {...getOverrideProps(
                overrides,
                "Flex.Flex[0].Flex[0].Flex[0].TextField[0]"
              )}
            ></TextField>
            <TextField
              display="flex"
              shrink="0"
              alignSelf="stretch"
              objectFit="cover"
              size="large"
              variation="default"
              {...getOverrideProps(
                overrides,
                "Flex.Flex[0].Flex[0].Flex[0].TextField[1]"
              )}
            ></TextField>
          </Flex>
          <Divider
            shrink="0"
            alignSelf="stretch"
            objectFit="cover"
            size="small"
            orientation="horizontal"
            {...getOverrideProps(overrides, "Flex.Flex[0].Flex[0].Divider[0]")}
          ></Divider>
          <Flex
            gap="24px"
            direction="column"
            shrink="0"
            alignSelf="stretch"
            objectFit="cover"
            position="relative"
            padding="0px 32px 0px 32px"
            {...getOverrideProps(overrides, "Flex.Flex[0].Flex[0].Flex[1]")}
          >
            <Text
              fontFamily="Inter"
              fontSize="16px"
              fontWeight="700"
              color="rgba(13,26,38,1)"
              lineHeight="24px"
              textAlign="left"
              display="flex"
              direction="column"
              justifyContent="flex-start"
              shrink="0"
              position="relative"
              padding="0px 0px 0px 0px"
              whiteSpace="pre-wrap"
              children="Shipping"
              {...getOverrideProps(
                overrides,
                "Flex.Flex[0].Flex[0].Flex[1].Text[0]"
              )}
            ></Text>
            <TextField
              display="flex"
              shrink="0"
              alignSelf="stretch"
              objectFit="cover"
              size="large"
              variation="default"
              {...getOverrideProps(
                overrides,
                "Flex.Flex[0].Flex[0].Flex[1].TextField[0]"
              )}
            ></TextField>
            <TextField
              display="flex"
              shrink="0"
              alignSelf="stretch"
              objectFit="cover"
              size="large"
              variation="default"
              {...getOverrideProps(
                overrides,
                "Flex.Flex[0].Flex[0].Flex[1].TextField[1]"
              )}
            ></TextField>
            <Flex
              gap="24px"
              direction="row"
              alignItems="flex-start"
              shrink="0"
              alignSelf="stretch"
              objectFit="cover"
              position="relative"
              padding="0px 0px 0px 0px"
              {...getOverrideProps(
                overrides,
                "Flex.Flex[0].Flex[0].Flex[1].Flex[0]"
              )}
            >
              <TextField
                width="289.5px"
                display="flex"
                grow="1"
                basis="289.5px"
                height="74px"
                size="large"
                variation="default"
                {...getOverrideProps(
                  overrides,
                  "Flex.Flex[0].Flex[0].Flex[1].Flex[0].TextField[0]"
                )}
              ></TextField>
              <SelectField
                width="289.5px"
                display="flex"
                grow="1"
                basis="289.5px"
                height="74px"
                size="large"
                variation="default"
                {...getOverrideProps(
                  overrides,
                  "Flex.Flex[0].Flex[0].Flex[1].Flex[0].SelectField[0]"
                )}
              ></SelectField>
            </Flex>
            <Flex
              gap="24px"
              direction="row"
              alignItems="flex-start"
              shrink="0"
              alignSelf="stretch"
              objectFit="cover"
              position="relative"
              padding="0px 0px 0px 0px"
              {...getOverrideProps(
                overrides,
                "Flex.Flex[0].Flex[0].Flex[1].Flex[1]"
              )}
            >
              <TextField
                width="289.5px"
                display="flex"
                grow="1"
                basis="289.5px"
                height="74px"
                size="large"
                variation="default"
                {...getOverrideProps(
                  overrides,
                  "Flex.Flex[0].Flex[0].Flex[1].Flex[1].TextField[0]"
                )}
              ></TextField>
              <SelectField
                width="289.5px"
                display="flex"
                grow="1"
                basis="289.5px"
                height="74px"
                size="large"
                variation="default"
                {...getOverrideProps(
                  overrides,
                  "Flex.Flex[0].Flex[0].Flex[1].Flex[1].SelectField[0]"
                )}
              ></SelectField>
            </Flex>
          </Flex>
          <Divider
            shrink="0"
            alignSelf="stretch"
            objectFit="cover"
            size="small"
            orientation="horizontal"
            {...getOverrideProps(overrides, "Flex.Flex[0].Flex[0].Divider[1]")}
          ></Divider>
          <Flex
            gap="24px"
            direction="column"
            shrink="0"
            alignSelf="stretch"
            objectFit="cover"
            position="relative"
            padding="0px 32px 0px 32px"
            {...getOverrideProps(overrides, "Flex.Flex[0].Flex[0].Flex[2]")}
          >
            <Text
              fontFamily="Inter"
              fontSize="16px"
              fontWeight="700"
              color="rgba(13,26,38,1)"
              lineHeight="24px"
              textAlign="left"
              display="flex"
              direction="column"
              justifyContent="flex-start"
              shrink="0"
              position="relative"
              padding="0px 0px 0px 0px"
              whiteSpace="pre-wrap"
              children="Card info"
              {...getOverrideProps(
                overrides,
                "Flex.Flex[0].Flex[0].Flex[2].Text[0]"
              )}
            ></Text>
            <TextField
              display="flex"
              shrink="0"
              alignSelf="stretch"
              objectFit="cover"
              size="large"
              variation="default"
              {...getOverrideProps(
                overrides,
                "Flex.Flex[0].Flex[0].Flex[2].TextField[0]"
              )}
            ></TextField>
            <TextField
              display="flex"
              shrink="0"
              alignSelf="stretch"
              objectFit="cover"
              size="large"
              variation="default"
              {...getOverrideProps(
                overrides,
                "Flex.Flex[0].Flex[0].Flex[2].TextField[1]"
              )}
            ></TextField>
            <Flex
              gap="24px"
              direction="row"
              alignItems="flex-start"
              shrink="0"
              alignSelf="stretch"
              objectFit="cover"
              position="relative"
              padding="0px 0px 0px 0px"
              {...getOverrideProps(
                overrides,
                "Flex.Flex[0].Flex[0].Flex[2].Flex[0]"
              )}
            >
              <SelectField
                width="289.5px"
                display="flex"
                grow="1"
                basis="289.5px"
                height="74px"
                size="large"
                variation="default"
                {...getOverrideProps(
                  overrides,
                  "Flex.Flex[0].Flex[0].Flex[2].Flex[0].SelectField[0]"
                )}
              ></SelectField>
              <SelectField
                width="289.5px"
                display="flex"
                grow="1"
                basis="289.5px"
                height="74px"
                size="large"
                variation="default"
                {...getOverrideProps(
                  overrides,
                  "Flex.Flex[0].Flex[0].Flex[2].Flex[0].SelectField[1]"
                )}
              ></SelectField>
            </Flex>
          </Flex>
        </Flex>
        <AppCart />
      </Flex>
    </Flex>
  );
}
